### ISSUE TITLE
Having trouble compiling this sketch

### ISSUE THREAD

**Issue by ctcooper1** [pixelmatix/Continuum#1]
Hello,

I am new to Arduino and I am having a bit of trouble compiling this sketch. I am using 32x32 hub75 (for testing), teensy 4.1, smartLED shield v5, and SmartMatrix4 on Arduino 1.8.13. Currently trying to compile GifInterpolation. 

I build custom light fixtures as art installations and started dabbling in led animation art. I liked the idea of adding encoders and potentiometer for playback speed, changing content, and controlling brightness. I have used AnimatedGifs in the past and it was quite simple getting it to work. And it's awesome!   

The only thing I have changed was for my current matrix hardware configuration in the .ino
This is the error I am getting. 
`'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'`

I really appreciate your help/advice in advance!

```
In file included from C:\Users\clear\AppData\Local\Temp\arduino_modified_sketch_687412\GifInterpolation.ino:75:0:

D:\Users\Documents\Arduino\libraries\SmartMatrix-master\src/MatrixHardware_Teensy4_ShieldV5.h:41:17: note: #pragma message: MatrixHardware: SmartLED Shield for Teensy 4 (V5)

pragma message "MatrixHardware: SmartLED Shield for Teensy 4 (V5)"
                
In file included from C:\Users\clear\AppData\Local\Temp\arduino_modified_sketch_687412\GifInterpolation.ino:76:0:

D:\Users\Documents\Arduino\libraries\SmartMatrix-master\src/SmartMatrix.h:40:21: note: #pragma message: SmartMatrix Library version 4.000.003

pragma message "SmartMatrix Library version 4.000.003

In file included from D:\Users\Documents\Arduino\libraries\Continuum-main/Layer_BackgroundInterpolation.h:153:0,

                 from C:\Users\clear\AppData\Local\Temp\arduino_modified_sketch_687412\GifInterpolation.ino:77:

D:\Users\Documents\Arduino\libraries\Continuum-main/Layer_BackgroundInterpolation_Impl.h: In instantiation of 'void SMLayerBackgroundInterpolation<RGB, optionFlags>::drawPixel(int16_t, int16_t, const RGB&) [with RGB = rgb24; unsigned int optionFlags = 0u; int16_t = short int]':

C:\Users\clear\AppData\Local\Temp\arduino_modified_sketch_687412\GifInterpolation.ino:188:60:   required from here

Layer_BackgroundInterpolation_Impl.h:375: error: 'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'

     if (this->rotation == rotation0) {
                     
Layer_BackgroundInterpolation_Impl.h:378: error: 'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'

     } else if (this->rotation == rotation180) {
                               
Layer_BackgroundInterpolation_Impl.h:381: error: 'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'

     } else if (this->rotation == rotation90) {
                              
D:\Users\Documents\Arduino\libraries\Continuum-main/Layer_BackgroundInterpolation_Impl.h: In instantiation of 'void SMLayerBackgroundInterpolation<RGB, optionFlags>::drawFastHLine(int16_t, int16_t, int16_t, const RGB&) [with RGB = rgb24; unsigned int optionFlags = 0u; int16_t = short int]':

D:\Users\Documents\Arduino\libraries\Continuum-main/Layer_BackgroundInterpolation_Impl.h:1021:22:   required from 'void SMLayerBackgroundInterpolation<RGB, optionFlags>::fillRectangle(int16_t, int16_t, int16_t, int16_t, const RGB&) [with RGB = rgb24; unsigned int optionFlags = 0u; int16_t = short int]'

D:\Users\Documents\Arduino\libraries\Continuum-main/Layer_BackgroundInterpolation_Impl.h:1027:18:   required from 'void SMLayerBackgroundInterpolation<RGB, optionFlags>::fillScreen(const RGB&) [with RGB = rgb24; unsigned int optionFlags = 0u]'

C:\Users\clear\AppData\Local\Temp\arduino_modified_sketch_687412\GifInterpolation.ino:180:37:   required from here

Layer_BackgroundInterpolation_Impl.h:436: error: 'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'

     if (this->rotation == rotation0) {
                  
Layer_BackgroundInterpolation_Impl.h:438: error: 'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'

     } else if (this->rotation == rotation180) {
                              
Layer_BackgroundInterpolation_Impl.h:440: error: 'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'

     } else if (this->rotation == rotation90) {
                               
Multiple libraries were found for "SD.h"

 Used: D:\Program Files\Arduino\hardware\teensy\avr\libraries\SD

 Not used: D:\Program Files\Arduino\libraries\SD

'class SMLayerBackgroundInterpolation<rgb24, 0u>' has no member named 'rotation'`
```

Thanks!
CT.

**Comment by embedded-creations** [comment]
Hi CT.! This sketch hadn't been updated for SmartMatrix Library 4.0, I just made and pushed the changes and it compiles on my machine but I'm not in a position to test it right now.  Can you let me know if it works for you?

I'm curious about your light fixtures, if you have any public photos or videos can you please share them?  Or you can contact me directly (through community.pixelmatix.com or the email on my site) if you want.

**Comment by ctcooper1** [comment]
Awesome, thanks!

I'll give it a go tonight and post back the results. 

Of course, you can check my work at my Instagram @caskandcutter

I'll send you an email as well.

I don't have any of my art pieces on there. Most are functional abstract lamps/fixtures. But here's the frame I've built for my newest art project. Still waiting on led components from China.  

Its 32"x32" with hard maple frame using chemcast black acrylic.

![20210707_081855](https://user-images.githubusercontent.com/86936691/124792972-61487800-df02-11eb-963c-22fee4e8d852.jpg)

Thanks! CT.

**Comment by ctcooper1** [comment]
The updated sketch seems to be working great! 

Didn't play with it too much but the playback speed potentiometer works awesome! Going to load up a few more animations and see how it does. 

Thanks for all your hard work. Where can I donate?

CT.

**Comment by embedded-creations** [comment]
Really want to see that piece lit up!  Your lamps on instagram look great!

Glad to hear you got it working.  I was playing with a logarithmic scale for the speed, and never got it quite dialed in but that's something I want to finish.  My focus has been on making a Wifi-enabled version of the project, and I'm very close, supporting up to 64x64 right now.  I added 2D and GIF decoding on top of WLED running on an ESP32, and then have another ESP32 driving the matrix.  It's not as silky smooth as the Teensy 4.1.  I have an idea of how to add Wifi support to the Teensy using a separate ESP8266 or ESP32, but that's still in the idea stage.

I host a LED Art chat today (and every Wednesday) at 1pm Pacific time here, you're more than welcome to join: https://hackaday.io/messages/room/289684

Thanks for asking about donating, here's a link!  https://github.com/pixelmatix/SmartMatrix#supporting-smartmatrix-library-development
